services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_calculator
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d finance_calculator"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build: .
    entrypoint: ["goose"]
    command:
      [
        "-dir", "/migrations",
        "postgres",
        "postgres://app_user:password@db:5432/finance_calculator?sslmode=disable",
        "up"
      ]
    volumes:
      - ./internal/db/migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      POSTGRES_CONNECTION_STRING: postgres://app_user:password@db:5432/finance_calculator?sslmode=disable
      ACCESS_SECRET: DEVENVIRONMENTSECRET
      REFRESH_SECRET: DEVENVREFRESHSECRET
      ENV: develop
      ALLOWED_ORIGIN: http://localhost:5173
    depends_on:
      migrate:
        condition: service_completed_successfully

volumes:
  postgres_data:
