// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: savings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavings = `-- name: CreateSavings :one
INSERT INTO savings (user_id,
    name,
    starting_capital,
    yearly_interest_rate,
    interest_rate_type,
    monthly_contribution,
    duration_years,
    tax_rate,
    yearly_inflation_rate,
    start_date,
    monthly_interest_rate,
    total_interest_earnings,
    total_deposited,
    rate_of_return,
    inflation_adjusted_ror
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, user_id, name, starting_capital, yearly_interest_rate, interest_rate_type, monthly_contribution, duration_years, tax_rate, yearly_inflation_rate, start_date, monthly_interest_rate, total_interest_earnings, rate_of_return, inflation_adjusted_ror, total_deposited, created_at
`

type CreateSavingsParams struct {
	UserID                pgtype.UUID
	Name                  string
	StartingCapital       int32
	YearlyInterestRate    string
	InterestRateType      string
	MonthlyContribution   int32
	DurationYears         int32
	TaxRate               string
	YearlyInflationRate   pgtype.Text
	StartDate             pgtype.Date
	MonthlyInterestRate   string
	TotalInterestEarnings int32
	TotalDeposited        int32
	RateOfReturn          string
	InflationAdjustedRor  string
}

func (q *Queries) CreateSavings(ctx context.Context, arg CreateSavingsParams) (Saving, error) {
	row := q.db.QueryRow(ctx, createSavings,
		arg.UserID,
		arg.Name,
		arg.StartingCapital,
		arg.YearlyInterestRate,
		arg.InterestRateType,
		arg.MonthlyContribution,
		arg.DurationYears,
		arg.TaxRate,
		arg.YearlyInflationRate,
		arg.StartDate,
		arg.MonthlyInterestRate,
		arg.TotalInterestEarnings,
		arg.TotalDeposited,
		arg.RateOfReturn,
		arg.InflationAdjustedRor,
	)
	var i Saving
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingCapital,
		&i.YearlyInterestRate,
		&i.InterestRateType,
		&i.MonthlyContribution,
		&i.DurationYears,
		&i.TaxRate,
		&i.YearlyInflationRate,
		&i.StartDate,
		&i.MonthlyInterestRate,
		&i.TotalInterestEarnings,
		&i.RateOfReturn,
		&i.InflationAdjustedRor,
		&i.TotalDeposited,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSavings = `-- name: DeleteSavings :execrows
DELETE FROM savings
WHERE id = $1 AND user_id = $2
`

type DeleteSavingsParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteSavings(ctx context.Context, arg DeleteSavingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavings, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSavings = `-- name: GetSavings :one
SELECT id, user_id, name, starting_capital, yearly_interest_rate, interest_rate_type, monthly_contribution, duration_years, tax_rate, yearly_inflation_rate, start_date, monthly_interest_rate, total_interest_earnings, rate_of_return, inflation_adjusted_ror, total_deposited, created_at FROM savings
WHERE id = $1 AND user_id = $2
`

type GetSavingsParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetSavings(ctx context.Context, arg GetSavingsParams) (Saving, error) {
	row := q.db.QueryRow(ctx, getSavings, arg.ID, arg.UserID)
	var i Saving
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingCapital,
		&i.YearlyInterestRate,
		&i.InterestRateType,
		&i.MonthlyContribution,
		&i.DurationYears,
		&i.TaxRate,
		&i.YearlyInflationRate,
		&i.StartDate,
		&i.MonthlyInterestRate,
		&i.TotalInterestEarnings,
		&i.RateOfReturn,
		&i.InflationAdjustedRor,
		&i.TotalDeposited,
		&i.CreatedAt,
	)
	return i, err
}

const getSavingsByUserID = `-- name: GetSavingsByUserID :many
SELECT id, name, starting_capital FROM savings
WHERE user_id = $1
`

type GetSavingsByUserIDRow struct {
	ID              pgtype.UUID
	Name            string
	StartingCapital int32
}

func (q *Queries) GetSavingsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetSavingsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getSavingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSavingsByUserIDRow
	for rows.Next() {
		var i GetSavingsByUserIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.StartingCapital); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSavingsInitialData = `-- name: GetSavingsInitialData :one
SELECT name,
    starting_capital,
    yearly_interest_rate,
    interest_rate_type,
    monthly_contribution,
    duration_years,
    tax_rate,
    yearly_inflation_rate,
    start_date
FROM savings
WHERE id = $1 AND user_id = $2
`

type GetSavingsInitialDataParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

type GetSavingsInitialDataRow struct {
	Name                string
	StartingCapital     int32
	YearlyInterestRate  string
	InterestRateType    string
	MonthlyContribution int32
	DurationYears       int32
	TaxRate             string
	YearlyInflationRate pgtype.Text
	StartDate           pgtype.Date
}

func (q *Queries) GetSavingsInitialData(ctx context.Context, arg GetSavingsInitialDataParams) (GetSavingsInitialDataRow, error) {
	row := q.db.QueryRow(ctx, getSavingsInitialData, arg.ID, arg.UserID)
	var i GetSavingsInitialDataRow
	err := row.Scan(
		&i.Name,
		&i.StartingCapital,
		&i.YearlyInterestRate,
		&i.InterestRateType,
		&i.MonthlyContribution,
		&i.DurationYears,
		&i.TaxRate,
		&i.YearlyInflationRate,
		&i.StartDate,
	)
	return i, err
}

const updateSavings = `-- name: UpdateSavings :one
UPDATE savings
SET name = $3,
    starting_capital = $4,
    yearly_interest_rate = $5,
    interest_rate_type = $6,
    monthly_contribution = $7,
    duration_years = $8,
    tax_rate = $9,
    yearly_inflation_rate = $10,
    start_date = $11,
    monthly_interest_rate = $12,
    total_interest_earnings = $13,
    total_deposited = $14,
    rate_of_return = $15,
    inflation_adjusted_ror = $16
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, starting_capital, yearly_interest_rate, interest_rate_type, monthly_contribution, duration_years, tax_rate, yearly_inflation_rate, start_date, monthly_interest_rate, total_interest_earnings, rate_of_return, inflation_adjusted_ror, total_deposited, created_at
`

type UpdateSavingsParams struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Name                  string
	StartingCapital       int32
	YearlyInterestRate    string
	InterestRateType      string
	MonthlyContribution   int32
	DurationYears         int32
	TaxRate               string
	YearlyInflationRate   pgtype.Text
	StartDate             pgtype.Date
	MonthlyInterestRate   string
	TotalInterestEarnings int32
	TotalDeposited        int32
	RateOfReturn          string
	InflationAdjustedRor  string
}

func (q *Queries) UpdateSavings(ctx context.Context, arg UpdateSavingsParams) (Saving, error) {
	row := q.db.QueryRow(ctx, updateSavings,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.StartingCapital,
		arg.YearlyInterestRate,
		arg.InterestRateType,
		arg.MonthlyContribution,
		arg.DurationYears,
		arg.TaxRate,
		arg.YearlyInflationRate,
		arg.StartDate,
		arg.MonthlyInterestRate,
		arg.TotalInterestEarnings,
		arg.TotalDeposited,
		arg.RateOfReturn,
		arg.InflationAdjustedRor,
	)
	var i Saving
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingCapital,
		&i.YearlyInterestRate,
		&i.InterestRateType,
		&i.MonthlyContribution,
		&i.DurationYears,
		&i.TaxRate,
		&i.YearlyInflationRate,
		&i.StartDate,
		&i.MonthlyInterestRate,
		&i.TotalInterestEarnings,
		&i.RateOfReturn,
		&i.InflationAdjustedRor,
		&i.TotalDeposited,
		&i.CreatedAt,
	)
	return i, err
}
