// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loan_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoanState = `-- name: CreateLoanState :one
INSERT INTO loan_state (payment_plan_id,
    date,
    payment,
    interest,
    other_payments,
    paydown,
    principal
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, payment_plan_id, date, payment, interest, other_payments, paydown, principal
`

type CreateLoanStateParams struct {
	PaymentPlanID pgtype.UUID
	Date          pgtype.Date
	Payment       int32
	Interest      int32
	OtherPayments int32
	Paydown       int32
	Principal     int32
}

func (q *Queries) CreateLoanState(ctx context.Context, arg CreateLoanStateParams) (LoanState, error) {
	row := q.db.QueryRow(ctx, createLoanState,
		arg.PaymentPlanID,
		arg.Date,
		arg.Payment,
		arg.Interest,
		arg.OtherPayments,
		arg.Paydown,
		arg.Principal,
	)
	var i LoanState
	err := row.Scan(
		&i.ID,
		&i.PaymentPlanID,
		&i.Date,
		&i.Payment,
		&i.Interest,
		&i.OtherPayments,
		&i.Paydown,
		&i.Principal,
	)
	return i, err
}

const deleteLoanStatesByPaymentPlanID = `-- name: DeleteLoanStatesByPaymentPlanID :exec
DELETE FROM loan_state
WHERE payment_plan_id = $1
`

func (q *Queries) DeleteLoanStatesByPaymentPlanID(ctx context.Context, paymentPlanID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLoanStatesByPaymentPlanID, paymentPlanID)
	return err
}

const getLoanStatesByPaymentPlanID = `-- name: GetLoanStatesByPaymentPlanID :many
SELECT id, payment_plan_id, date, payment, interest, other_payments, paydown, principal FROM loan_state
WHERE payment_plan_id = $1
ORDER BY date ASC
`

func (q *Queries) GetLoanStatesByPaymentPlanID(ctx context.Context, paymentPlanID pgtype.UUID) ([]LoanState, error) {
	rows, err := q.db.Query(ctx, getLoanStatesByPaymentPlanID, paymentPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanState
	for rows.Next() {
		var i LoanState
		if err := rows.Scan(
			&i.ID,
			&i.PaymentPlanID,
			&i.Date,
			&i.Payment,
			&i.Interest,
			&i.OtherPayments,
			&i.Paydown,
			&i.Principal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
