// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoan = `-- name: CreateLoan :one
INSERT INTO loans(user_id,
    name,
    starting_principal,
    yearly_interest_rate,
    monthly_payment,
    escrow_payment,
    start_date,
    monthly_interest_rate,
    duration_months,
    total_expenditure,
    total_paid,
    cost_of_credit
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, user_id, name, starting_principal, yearly_interest_rate, monthly_payment, escrow_payment, start_date, monthly_interest_rate, duration_months, total_expenditure, total_paid, cost_of_credit, created_at
`

type CreateLoanParams struct {
	UserID              pgtype.UUID
	Name                string
	StartingPrincipal   int32
	YearlyInterestRate  string
	MonthlyPayment      int32
	EscrowPayment       int32
	StartDate           pgtype.Timestamptz
	MonthlyInterestRate string
	DurationMonths      int32
	TotalExpenditure    int32
	TotalPaid           int32
	CostOfCredit        string
}

func (q *Queries) CreateLoan(ctx context.Context, arg CreateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, createLoan,
		arg.UserID,
		arg.Name,
		arg.StartingPrincipal,
		arg.YearlyInterestRate,
		arg.MonthlyPayment,
		arg.EscrowPayment,
		arg.StartDate,
		arg.MonthlyInterestRate,
		arg.DurationMonths,
		arg.TotalExpenditure,
		arg.TotalPaid,
		arg.CostOfCredit,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingPrincipal,
		&i.YearlyInterestRate,
		&i.MonthlyPayment,
		&i.EscrowPayment,
		&i.StartDate,
		&i.MonthlyInterestRate,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLoan = `-- name: DeleteLoan :exec
DELETE FROM loans
WHERE id = $1 AND user_id = $2
`

type DeleteLoanParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteLoan(ctx context.Context, arg DeleteLoanParams) error {
	_, err := q.db.Exec(ctx, deleteLoan, arg.ID, arg.UserID)
	return err
}

const getLoan = `-- name: GetLoan :one
SELECT id, user_id, name, starting_principal, yearly_interest_rate, monthly_payment, escrow_payment, start_date, monthly_interest_rate, duration_months, total_expenditure, total_paid, cost_of_credit, created_at FROM loans
WHERE id = $1 AND user_id = $2
`

type GetLoanParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetLoan(ctx context.Context, arg GetLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, getLoan, arg.ID, arg.UserID)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingPrincipal,
		&i.YearlyInterestRate,
		&i.MonthlyPayment,
		&i.EscrowPayment,
		&i.StartDate,
		&i.MonthlyInterestRate,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
		&i.CreatedAt,
	)
	return i, err
}

const getLoansByUserID = `-- name: GetLoansByUserID :many
SELECT id, name, starting_principal FROM loans
WHERE user_id = $1
`

type GetLoansByUserIDRow struct {
	ID                pgtype.UUID
	Name              string
	StartingPrincipal int32
}

func (q *Queries) GetLoansByUserID(ctx context.Context, userID pgtype.UUID) ([]GetLoansByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getLoansByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLoansByUserIDRow
	for rows.Next() {
		var i GetLoansByUserIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.StartingPrincipal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoan = `-- name: UpdateLoan :one
UPDATE loans
SET name = $3,
    starting_principal = $4,
    yearly_interest_rate = $5,
    monthly_payment = $6,
    escrow_payment = $7,
    start_date = $8,
    monthly_interest_rate = $9,
    duration_months = $10,
    total_expenditure = $11,
    total_paid = $12,
    cost_of_credit = $13
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, starting_principal, yearly_interest_rate, monthly_payment, escrow_payment, start_date, monthly_interest_rate, duration_months, total_expenditure, total_paid, cost_of_credit, created_at
`

type UpdateLoanParams struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Name                string
	StartingPrincipal   int32
	YearlyInterestRate  string
	MonthlyPayment      int32
	EscrowPayment       int32
	StartDate           pgtype.Timestamptz
	MonthlyInterestRate string
	DurationMonths      int32
	TotalExpenditure    int32
	TotalPaid           int32
	CostOfCredit        string
}

func (q *Queries) UpdateLoan(ctx context.Context, arg UpdateLoanParams) (Loan, error) {
	row := q.db.QueryRow(ctx, updateLoan,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.StartingPrincipal,
		arg.YearlyInterestRate,
		arg.MonthlyPayment,
		arg.EscrowPayment,
		arg.StartDate,
		arg.MonthlyInterestRate,
		arg.DurationMonths,
		arg.TotalExpenditure,
		arg.TotalPaid,
		arg.CostOfCredit,
	)
	var i Loan
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingPrincipal,
		&i.YearlyInterestRate,
		&i.MonthlyPayment,
		&i.EscrowPayment,
		&i.StartDate,
		&i.MonthlyInterestRate,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
		&i.CreatedAt,
	)
	return i, err
}
