// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: loan_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLoanState = `-- name: CreateLoanState :one
INSERT INTO loan_state (loan_id,
    date,
    payment,
    interest,
    other_payments,
    paydown,
    principal
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, loan_id, date, payment, interest, other_payments, paydown, principal
`

type CreateLoanStateParams struct {
	LoanID        pgtype.UUID
	Date          pgtype.Timestamptz
	Payment       int32
	Interest      int32
	OtherPayments int32
	Paydown       int32
	Principal     int32
}

func (q *Queries) CreateLoanState(ctx context.Context, arg CreateLoanStateParams) (LoanState, error) {
	row := q.db.QueryRow(ctx, createLoanState,
		arg.LoanID,
		arg.Date,
		arg.Payment,
		arg.Interest,
		arg.OtherPayments,
		arg.Paydown,
		arg.Principal,
	)
	var i LoanState
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Date,
		&i.Payment,
		&i.Interest,
		&i.OtherPayments,
		&i.Paydown,
		&i.Principal,
	)
	return i, err
}

const deleteLoanStatesByLoanID = `-- name: DeleteLoanStatesByLoanID :exec
DELETE FROM loan_state
WHERE loan_id = $1
`

func (q *Queries) DeleteLoanStatesByLoanID(ctx context.Context, loanID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLoanStatesByLoanID, loanID)
	return err
}

const getLoanStatesByLoanID = `-- name: GetLoanStatesByLoanID :many
SELECT id, loan_id, date, payment, interest, other_payments, paydown, principal FROM loan_state
WHERE loan_id = $1
ORDER BY date ASC
`

func (q *Queries) GetLoanStatesByLoanID(ctx context.Context, loanID pgtype.UUID) ([]LoanState, error) {
	rows, err := q.db.Query(ctx, getLoanStatesByLoanID, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoanState
	for rows.Next() {
		var i LoanState
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.Date,
			&i.Payment,
			&i.Interest,
			&i.OtherPayments,
			&i.Paydown,
			&i.Principal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
