// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Loan struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Name                string
	StartingPrincipal   int32
	YearlyInterestRate  string
	MonthlyPayment      int32
	EscrowPayment       int32
	StartDate           pgtype.Date
	MonthlyInterestRate string
	DefaultPaymentPlan  pgtype.UUID
	CreatedAt           pgtype.Timestamptz
}

type LoanState struct {
	ID            pgtype.UUID
	PaymentPlanID pgtype.UUID
	Date          pgtype.Date
	Payment       int32
	Interest      int32
	OtherPayments int32
	Paydown       int32
	Principal     int32
}

type PaymentPlan struct {
	ID               pgtype.UUID
	LoanID           pgtype.UUID
	Name             string
	DurationMonths   int32
	TotalExpenditure int32
	TotalPaid        int32
	CostOfCredit     string
}

type PrincipalPayment struct {
	ID            pgtype.UUID
	PaymentPlanID pgtype.UUID
	AmountPaid    int32
	Date          pgtype.Date
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	Revoked   pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type Saving struct {
	ID                    pgtype.UUID
	UserID                pgtype.UUID
	Name                  string
	StartingCapital       int32
	YearlyInterestRate    string
	InterestRateType      string
	MonthlyContribution   int32
	DurationYears         int32
	TaxRate               string
	YearlyInflationRate   pgtype.Text
	StartDate             pgtype.Date
	MonthlyInterestRate   string
	TotalInterestEarnings int32
	RateOfReturn          string
	InflationAdjustedRor  string
	TotalDeposited        int32
	CreatedAt             pgtype.Timestamptz
}

type SavingsState struct {
	ID           pgtype.UUID
	SavingsID    pgtype.UUID
	Date         pgtype.Date
	Interest     int32
	Tax          int32
	Contribution int32
	Increase     int32
	Capital      int32
}

type User struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	Username     string
	CreatedAt    pgtype.Timestamp
}
