// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment_plans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentPlan = `-- name: CreatePaymentPlan :one
INSERT INTO payment_plans (
    loan_id,
    name,
    duration_months,
    total_expenditure,
    total_paid,
    cost_of_credit
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, loan_id, name, duration_months, total_expenditure, total_paid, cost_of_credit
`

type CreatePaymentPlanParams struct {
	LoanID           pgtype.UUID
	Name             string
	DurationMonths   int32
	TotalExpenditure int32
	TotalPaid        int32
	CostOfCredit     string
}

func (q *Queries) CreatePaymentPlan(ctx context.Context, arg CreatePaymentPlanParams) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, createPaymentPlan,
		arg.LoanID,
		arg.Name,
		arg.DurationMonths,
		arg.TotalExpenditure,
		arg.TotalPaid,
		arg.CostOfCredit,
	)
	var i PaymentPlan
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Name,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
	)
	return i, err
}

const deletePaymentPlan = `-- name: DeletePaymentPlan :exec
DELETE FROM payment_plans
WHERE id = $1
`

func (q *Queries) DeletePaymentPlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePaymentPlan, id)
	return err
}

const getPaymentPlan = `-- name: GetPaymentPlan :one
SELECT id, loan_id, name, duration_months, total_expenditure, total_paid, cost_of_credit FROM payment_plans
WHERE id = $1
`

func (q *Queries) GetPaymentPlan(ctx context.Context, id pgtype.UUID) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, getPaymentPlan, id)
	var i PaymentPlan
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Name,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
	)
	return i, err
}

const getPaymentPlanByIDAndLoanID = `-- name: GetPaymentPlanByIDAndLoanID :one
SELECT id, loan_id, name, duration_months, total_expenditure, total_paid, cost_of_credit FROM payment_plans
WHERE id = $1 AND loan_id = $2
`

type GetPaymentPlanByIDAndLoanIDParams struct {
	ID     pgtype.UUID
	LoanID pgtype.UUID
}

func (q *Queries) GetPaymentPlanByIDAndLoanID(ctx context.Context, arg GetPaymentPlanByIDAndLoanIDParams) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, getPaymentPlanByIDAndLoanID, arg.ID, arg.LoanID)
	var i PaymentPlan
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Name,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
	)
	return i, err
}

const getPaymentPlansByLoanID = `-- name: GetPaymentPlansByLoanID :many
SELECT id, loan_id, name, duration_months, total_expenditure, total_paid, cost_of_credit FROM payment_plans
WHERE loan_id = $1
`

func (q *Queries) GetPaymentPlansByLoanID(ctx context.Context, loanID pgtype.UUID) ([]PaymentPlan, error) {
	rows, err := q.db.Query(ctx, getPaymentPlansByLoanID, loanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentPlan
	for rows.Next() {
		var i PaymentPlan
		if err := rows.Scan(
			&i.ID,
			&i.LoanID,
			&i.Name,
			&i.DurationMonths,
			&i.TotalExpenditure,
			&i.TotalPaid,
			&i.CostOfCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentPlan = `-- name: UpdatePaymentPlan :one
UPDATE payment_plans
SET name = $2,
    duration_months = $3,
    total_expenditure = $4,
    total_paid = $5,
    cost_of_credit = $6
WHERE id = $1
RETURNING id, loan_id, name, duration_months, total_expenditure, total_paid, cost_of_credit
`

type UpdatePaymentPlanParams struct {
	ID               pgtype.UUID
	Name             string
	DurationMonths   int32
	TotalExpenditure int32
	TotalPaid        int32
	CostOfCredit     string
}

func (q *Queries) UpdatePaymentPlan(ctx context.Context, arg UpdatePaymentPlanParams) (PaymentPlan, error) {
	row := q.db.QueryRow(ctx, updatePaymentPlan,
		arg.ID,
		arg.Name,
		arg.DurationMonths,
		arg.TotalExpenditure,
		arg.TotalPaid,
		arg.CostOfCredit,
	)
	var i PaymentPlan
	err := row.Scan(
		&i.ID,
		&i.LoanID,
		&i.Name,
		&i.DurationMonths,
		&i.TotalExpenditure,
		&i.TotalPaid,
		&i.CostOfCredit,
	)
	return i, err
}
