// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principal_payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPrincipalPayment = `-- name: CreatePrincipalPayment :one
INSERT INTO principal_payments (
    payment_plan_id,
    amount_paid,
    date
)
VALUES ($1, $2, $3)
RETURNING id, payment_plan_id, amount_paid, date
`

type CreatePrincipalPaymentParams struct {
	PaymentPlanID pgtype.UUID
	AmountPaid    int32
	Date          pgtype.Timestamptz
}

func (q *Queries) CreatePrincipalPayment(ctx context.Context, arg CreatePrincipalPaymentParams) (PrincipalPayment, error) {
	row := q.db.QueryRow(ctx, createPrincipalPayment, arg.PaymentPlanID, arg.AmountPaid, arg.Date)
	var i PrincipalPayment
	err := row.Scan(
		&i.ID,
		&i.PaymentPlanID,
		&i.AmountPaid,
		&i.Date,
	)
	return i, err
}

const deletePrincipalPaymentsByPaymentPlanID = `-- name: DeletePrincipalPaymentsByPaymentPlanID :exec
DELETE FROM principal_payments
WHERE payment_plan_id = $1
`

func (q *Queries) DeletePrincipalPaymentsByPaymentPlanID(ctx context.Context, paymentPlanID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePrincipalPaymentsByPaymentPlanID, paymentPlanID)
	return err
}

const getPrincipalPaymentsByPaymentPlanID = `-- name: GetPrincipalPaymentsByPaymentPlanID :many
SELECT id, payment_plan_id, amount_paid, date FROM principal_payments
WHERE payment_plan_id = $1
ORDER BY date ASC
`

func (q *Queries) GetPrincipalPaymentsByPaymentPlanID(ctx context.Context, paymentPlanID pgtype.UUID) ([]PrincipalPayment, error) {
	rows, err := q.db.Query(ctx, getPrincipalPaymentsByPaymentPlanID, paymentPlanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrincipalPayment
	for rows.Next() {
		var i PrincipalPayment
		if err := rows.Scan(
			&i.ID,
			&i.PaymentPlanID,
			&i.AmountPaid,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
