// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: savings_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavingsState = `-- name: CreateSavingsState :one
INSERT INTO savings_state (savings_id,
    date,
    interest,
    tax,
    contribution,
    increase,
    capital
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, savings_id, date, interest, tax, contribution, increase, capital
`

type CreateSavingsStateParams struct {
	SavingsID    pgtype.UUID
	Date         pgtype.Timestamptz
	Interest     int32
	Tax          int32
	Contribution int32
	Increase     int32
	Capital      int32
}

func (q *Queries) CreateSavingsState(ctx context.Context, arg CreateSavingsStateParams) (SavingsState, error) {
	row := q.db.QueryRow(ctx, createSavingsState,
		arg.SavingsID,
		arg.Date,
		arg.Interest,
		arg.Tax,
		arg.Contribution,
		arg.Increase,
		arg.Capital,
	)
	var i SavingsState
	err := row.Scan(
		&i.ID,
		&i.SavingsID,
		&i.Date,
		&i.Interest,
		&i.Tax,
		&i.Contribution,
		&i.Increase,
		&i.Capital,
	)
	return i, err
}

const deleteSavingsStatesBySavingsID = `-- name: DeleteSavingsStatesBySavingsID :exec
DELETE FROM savings_state
WHERE savings_id = $1
`

func (q *Queries) DeleteSavingsStatesBySavingsID(ctx context.Context, savingsID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSavingsStatesBySavingsID, savingsID)
	return err
}

const getSavingsStatesBySavingsID = `-- name: GetSavingsStatesBySavingsID :many
SELECT id, savings_id, date, interest, tax, contribution, increase, capital FROM savings_state
WHERE savings_id = $1
ORDER BY date ASC
`

func (q *Queries) GetSavingsStatesBySavingsID(ctx context.Context, savingsID pgtype.UUID) ([]SavingsState, error) {
	rows, err := q.db.Query(ctx, getSavingsStatesBySavingsID, savingsID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavingsState
	for rows.Next() {
		var i SavingsState
		if err := rows.Scan(
			&i.ID,
			&i.SavingsID,
			&i.Date,
			&i.Interest,
			&i.Tax,
			&i.Contribution,
			&i.Increase,
			&i.Capital,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
