// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: savings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavings = `-- name: CreateSavings :one
INSERT INTO savings (user_id,
    name,
    starting_capital,
    yearly_interest_rate,
    interest_rate_type,
    monthly_contribution,
    duration_years,
    tax_rate,
    yearly_inflation_rate,
    start_date,
    monthly_interest_rate,
    total_interest_earnings,
    total_deposited,
    rate_of_return,
    inflation_adjusted_ror
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, user_id, name, starting_capital, yearly_interest_rate, interest_rate_type, monthly_contribution, duration_years, tax_rate, yearly_inflation_rate, start_date, monthly_interest_rate, total_interest_earnings, rate_of_return, inflation_adjusted_ror, created_at, total_deposited
`

type CreateSavingsParams struct {
	UserID                pgtype.UUID
	Name                  string
	StartingCapital       int32
	YearlyInterestRate    string
	InterestRateType      string
	MonthlyContribution   int32
	DurationYears         int32
	TaxRate               string
	YearlyInflationRate   pgtype.Text
	StartDate             pgtype.Timestamptz
	MonthlyInterestRate   string
	TotalInterestEarnings int32
	TotalDeposited        int32
	RateOfReturn          string
	InflationAdjustedRor  string
}

func (q *Queries) CreateSavings(ctx context.Context, arg CreateSavingsParams) (Saving, error) {
	row := q.db.QueryRow(ctx, createSavings,
		arg.UserID,
		arg.Name,
		arg.StartingCapital,
		arg.YearlyInterestRate,
		arg.InterestRateType,
		arg.MonthlyContribution,
		arg.DurationYears,
		arg.TaxRate,
		arg.YearlyInflationRate,
		arg.StartDate,
		arg.MonthlyInterestRate,
		arg.TotalInterestEarnings,
		arg.TotalDeposited,
		arg.RateOfReturn,
		arg.InflationAdjustedRor,
	)
	var i Saving
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingCapital,
		&i.YearlyInterestRate,
		&i.InterestRateType,
		&i.MonthlyContribution,
		&i.DurationYears,
		&i.TaxRate,
		&i.YearlyInflationRate,
		&i.StartDate,
		&i.MonthlyInterestRate,
		&i.TotalInterestEarnings,
		&i.RateOfReturn,
		&i.InflationAdjustedRor,
		&i.CreatedAt,
		&i.TotalDeposited,
	)
	return i, err
}

const deleteSavings = `-- name: DeleteSavings :exec
DELETE FROM savings
WHERE id = $1 AND user_id = $2
`

type DeleteSavingsParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteSavings(ctx context.Context, arg DeleteSavingsParams) error {
	_, err := q.db.Exec(ctx, deleteSavings, arg.ID, arg.UserID)
	return err
}

const getSavings = `-- name: GetSavings :one
SELECT id, user_id, name, starting_capital, yearly_interest_rate, interest_rate_type, monthly_contribution, duration_years, tax_rate, yearly_inflation_rate, start_date, monthly_interest_rate, total_interest_earnings, rate_of_return, inflation_adjusted_ror, created_at, total_deposited FROM savings
WHERE id = $1 AND user_id = $2
`

type GetSavingsParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) GetSavings(ctx context.Context, arg GetSavingsParams) (Saving, error) {
	row := q.db.QueryRow(ctx, getSavings, arg.ID, arg.UserID)
	var i Saving
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.StartingCapital,
		&i.YearlyInterestRate,
		&i.InterestRateType,
		&i.MonthlyContribution,
		&i.DurationYears,
		&i.TaxRate,
		&i.YearlyInflationRate,
		&i.StartDate,
		&i.MonthlyInterestRate,
		&i.TotalInterestEarnings,
		&i.RateOfReturn,
		&i.InflationAdjustedRor,
		&i.CreatedAt,
		&i.TotalDeposited,
	)
	return i, err
}

const getSavingsByUserID = `-- name: GetSavingsByUserID :many
SELECT id, name, starting_capital FROM savings
WHERE user_id = $1
`

type GetSavingsByUserIDRow struct {
	ID              pgtype.UUID
	Name            string
	StartingCapital int32
}

func (q *Queries) GetSavingsByUserID(ctx context.Context, userID pgtype.UUID) ([]GetSavingsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getSavingsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSavingsByUserIDRow
	for rows.Next() {
		var i GetSavingsByUserIDRow
		if err := rows.Scan(&i.ID, &i.Name, &i.StartingCapital); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
